# Generated by Django 3.1 on 2020-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accolade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('start_from', models.CharField(max_length=50)),
                ('till', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('role_description', models.CharField(max_length=50)),
                ('start_from', models.CharField(max_length=50)),
                ('till', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('contact', models.CharField(default='0', max_length=12)),
                ('email', models.CharField(default='-', max_length=50)),
                ('linkedin', models.CharField(default='-', max_length=50)),
                ('github', models.CharField(default='-', max_length=50)),
                ('site_name', models.CharField(default='-', max_length=50)),
                ('resume', models.FileField(upload_to='media/')),
                ('cover_letter', models.FileField(upload_to='media/')),
                ('user_pic', models.TextField(default='-')),
                ('user_pic_url', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=50)),
            ],
        ),
    ]
