# Generated by Django 3.1 on 2020-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('start_from', models.CharField(max_length=50)),
                ('till', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
