# Generated by Django 3.1 on 2020-08-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0005_auto_20200827_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='user_pic_url',
        ),
    ]
