# Generated by Django 3.1 on 2020-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0006_remove_main_user_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
