# Generated by Django 3.1 on 2020-08-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0009_education_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pic',
            field=models.ImageField(default='-', upload_to=''),
        ),
    ]
