# Generated by Django 3.1 on 2020-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0011_auto_20200830_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='role',
            field=models.TextField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.TextField(default='-', max_length=1500),
            preserve_default=False,
        ),
    ]
