# Generated by Django 3.1 on 2020-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0012_auto_20200830_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
