# Generated by Django 3.1 on 2020-09-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0013_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='user_pic',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='linkedin',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
