# Generated by Django 3.1 on 2020-09-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0014_auto_20200902_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='designation',
        ),
    ]
