# Generated by Django 3.1 on 2020-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0015_remove_recommendations_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='url',
            field=models.SlugField(null=True),
        ),
    ]
