# Generated by Django 3.1 on 2020-09-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0016_main_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='url',
        ),
    ]
